### ISSUE TITLE
Correct time zone handling

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach-django#15]
There are a number of test failures which suggest the current approach to time zones isn't correct.

For example:
```
======================================================================
FAIL: test_dates_trunc_datetime_fields (dates.tests.DatesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/test/utils.py", line 373, in inner
    return func(*args, **kwargs)
  File "/home/tim/code/django/tests/dates/tests.py", line 124, in test_dates_trunc_datetime_fields
    datetime.date(2015, 10, 22),
AssertionError: Sequences differ: <QuerySet [datetime.date(2015, 10, 20), datetime.date(2015, 10, 21)]> != [datetime.date(2015, 10, 21), datetime.date(2015, 10, 22)]

First differing element 0:
datetime.date(2015, 10, 20)
datetime.date(2015, 10, 21)

- <QuerySet [datetime.date(2015, 10, 20), datetime.date(2015, 10, 21)]>
? ----------                          ^                            ^  -

+ [datetime.date(2015, 10, 21), datetime.date(2015, 10, 22)]
?                           ^                            ^


======================================================================
FAIL: test_related_model_traverse (dates.tests.DatesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/dates/tests.py", line 49, in test_related_model_traverse
    datetime.date(2010, 1, 1),
AssertionError: Sequences differ: <QuerySet [datetime.date(2004, 12, 31), datetime.date(2009, 12, 31)]> != [datetime.date(2005, 1, 1), datetime.date(2010, 1, 1)]

First differing element 0:
datetime.date(2004, 12, 31)
datetime.date(2005, 1, 1)

- <QuerySet [datetime.date(2004, 12, 31), datetime.date(2009, 12, 31)]>
? ----------                  ^   -  -                     -   -  -   -

+ [datetime.date(2005, 1, 1), datetime.date(2010, 1, 1)]
?                   ^                         +
```

**Comment by timgraham** [comment]
https://github.com/cockroachdb/cockroach-django/issues/32 explains at least some of the failures.

**Comment by timgraham** [comment]
I haven't seen any other unexplained issues at this time, so closing this.
