### ISSUE TITLE
Unknown signatures for math database functions

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach-django#16]
There are a number of errors similar to this:
```
======================================================================
ERROR: test_null (db_functions.math.test_sqrt.SqrtTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedFunction: unknown signature: sqrt(int)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/django/tests/db_functions/math/test_sqrt.py", line 16, in test_null
    obj = IntegerModel.objects.annotate(null_sqrt=Sqrt('normal')).first()
  File "/home/tim/code/django/django/db/models/query.py", line 653, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/home/tim/code/django/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/home/tim/code/django/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tim/code/django/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tim/code/django/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: unknown signature: sqrt(int)
```
Should I prepare a list of types that cockroachdb's [math and numberic functions](https://www.cockroachlabs.com/docs/stable/functions-and-operators.htm#math-and-numeric-functions) should add support for or should the Django adapter take care of casting based on the currently supported types?

For example, In the latter case, since `tan` supports flat but not decimal or integer, the code would look  like this:
```python
from django.db.models import DecimalField, FloatField, IntegerField
from django.db.models.functions import Cast, Length, Tan

def tan(self, compiler, connection, **extra_context):
    clone = self.copy()
    clone.set_source_expressions([
        Cast(expression, FloatField()) if isinstance(expression.output_field, (DecimalField, IntegerField))
        else expression for expression in self.get_source_expressions()[::-1]
    ])
    return clone.as_sql(compiler, connection, **extra_context)

def register_expressions():
    Tan.as_cockroachdb = tan
```

**Comment by timgraham** [comment]
All unknown signatures errors in `db_functions.math` tests:
```
acos, asin, atan, cos, cot, degress, randians, sin, sqrt, tan: decimal, int2, and int
atan2(decimal, decimal)
atan2(int2, int)
ceiling(int2), ceiling(int)
exp(int2), exp(int)
floor(int2), floor(int)
ln(int2), ln(int)
log(decimal, decimal), log(float, float), log(int2, int)
round(int2), round(int)
```

**Comment by timgraham** [comment]
@jordanlewis feedback on this one?

**Comment by jordanlewis** [comment]
Oh, wait, I do think we have implementations for many of these, but just for float datatypes..

**Comment by timgraham** [comment]
Right, so I'll try the workaround code I proposed if the other signatures won't be added soon.

**Comment by jordanlewis** [comment]
Sorry, I gave feedback on the wrong thing. The workaround looks great. Thanks for looking into it.
