### ISSUE TITLE
Non-ASCII file tests fail on CI

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach-django#44]
See https://docs.djangoproject.com/en/dev/ref/unicode/#files

I tried adding `export LANG="en_US.UTF-8"` to `build-teamcity-sh` but it didn't help.

Example failure:
```
 ======================================================================
[23:08:19]
[Step 3/3] ERROR: test_content_saving (file_storage.tests.ContentFileStorageTestCase)
[23:08:19]
[Step 3/3] ----------------------------------------------------------------------
[23:08:19]
[Step 3/3] Traceback (most recent call last):
[23:08:19]
[Step 3/3]   File "/home/agent/work/391b6e30ae43aafa/_django_repo/tests/file_storage/tests.py", line 968, in test_content_saving
[23:08:19]
[Step 3/3]     self.storage.save('unicode.txt', ContentFile("espa\xf1ol"))
[23:08:19]
[Step 3/3]   File "/home/agent/work/391b6e30ae43aafa/_django_repo/django/core/files/storage.py", line 52, in save
[23:08:19]
[Step 3/3]     return self._save(name, content)
[23:08:19]
[Step 3/3]   File "/home/agent/work/391b6e30ae43aafa/_django_repo/django/core/files/storage.py", line 274, in _save
[23:08:19]
[Step 3/3]     _file.write(chunk)
[23:08:19]
[Step 3/3] UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 4: ordinal not in range(128)
```

**Comment by timgraham** [comment]
@rohany any idea?

**Comment by rohany** [comment]
No clue about this. You can run `./docker.sh teamcity-build/build-teamcity.sh`, to mimic what the teamcity agent is doing to run the CI if that helps.

**Comment by rohany** [comment]
Actually, maybe adding that as an environment variable when running the docker image might help? You could add `--env=LANG="en_US.UTF-8"` to the container invocation command at the bottom of docker.sh.

**Comment by timgraham** [comment]
Fixed by https://github.com/cockroachdb/cockroach-django/pull/45.
