### ISSUE TITLE
Unsupported query: unknown signature: avg(interval)

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach-django#72]
Use the `AVG` database function on an interval column isn't supported by cockroachdb: 
```sql
SELECT AVG("aggregation_publisher"."duration") AS "duration__avg"
FROM "aggregation_publisher";
```
It might be possible to workaround this [as done for Oracle](https://github.com/django/django/blob/39791c8e6de3a71879eb26dd9f8d01273847f395/django/db/models/functions/mixins.py#L31-L39).

Django test failure:
```
======================================================================
ERROR: test_avg_duration_field (aggregation.tests.AggregateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedFunction: unknown signature: avg(interval)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/django/tests/aggregation/tests.py", line 465, in test_avg_duration_field
    Publisher.objects.aggregate(Avg('duration', output_field=DurationField())),
  File "/home/tim/code/django/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/code/django/django/db/models/query.py", line 379, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "/home/tim/code/django/django/db/models/sql/query.py", line 489, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tim/code/django/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: unknown signature: avg(interval)

```

**Comment by rafiss** [comment]
Linking to CockroachDB issue: https://github.com/cockroachdb/cockroach/issues/42449
